spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver

  application:
    name: spring-batch-demo
  batch:
    job:
      enabled: false  # disable job run at startup
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
